<?xml version="1.0" encoding="utf-8"?>
<Project>

  <!-- Import central CEF version configuration -->
    <Import Project="$(MSBuildThisFileDirectory)\CefVersion.props" Condition="'$(CefVersion)' == ''" />

    <PropertyGroup>
        <DotnetVersion>net10.0</DotnetVersion>
        <LangVersion>latest</LangVersion>
        <AvaloniaVersion>12.1.2</AvaloniaVersion>
        <CefUseCustomSubProcess>true</CefUseCustomSubProcess>
        <CefGluePackageNameSuffix>Next.</CefGluePackageNameSuffix>
        <CefGluePackageNamePrefix>CefGlue.$(CefGluePackageNameSuffix)</CefGluePackageNamePrefix>
    </PropertyGroup>
    
    <PropertyGroup>
        <PackageOutputPath>$(MSBuildThisFileDirectory)Nuget\output</PackageOutputPath>
        <VersionPrefix>$(CefGlueVersion)</VersionPrefix>
        <Authors>XiliumHQ,OutSystems,DEON</Authors>
        <Product>CefGlue</Product>
        <AssemblyTitle>CefGlue</AssemblyTitle>
        <Description>CefGlue is a .NET binding for The Chromium Embedded Framework (CEF) by Marshall
            A. Greenblatt.</Description>
        <Copyright>Copyright &#xA9; XiliumHQ 2021. Copyright &#xA9; OutSystems 2021. Copyright &#xA9; DEON 2026.</Copyright>
        <PackageDescription>ChromiumEmbedded. $(Description)</PackageDescription>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>cef, chromium, chrome browser, cefglue</PackageTags>
        <!-- <PackageIcon></PackageIcon> -->
        <IncludeSymbols>false</IncludeSymbols>
        <IncludeSource>false</IncludeSource>
        <RepositoryUrl>https://github.com/Deon-Berlin/CefGlue</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <NoWarn>$(NoWarn);NU5100;NU5118;CS1591;NU1507</NoWarn>
    </PropertyGroup>

    <!-- Generate documentation in Release builds. -->
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

</Project>
